platform :ios, '7.0'
pod 'PSPDFTextView', :git => 'https://github.com/hpique/PSPDFTextView.git', :branch=>'agnes'
pod 'MMDrawerController', '~> 0.5'
pod 'MCSwipeTableViewCell', :git => 'https://github.com/hpique/MCSwipeTableViewCell.git'
pod 'SSZipArchive', '~> 0.3'
pod 'HPReorderTableView', :git => 'https://github.com/hpique/HPReorderTableView.git'
pod 'iOS7Colors', '~> 2.0.0'
pod 'TTTAttributedLabel', :git => 'https://github.com/hpique/TTTAttributedLabel.git'
pod 'MHWDirectoryWatcher', '~> 0.0'
pod 'ColorUtils', :git => 'https://github.com/hpique/ColorUtils.git', :branch=>'agnes'
