platform :ios, '7.0'
pod 'PSPDFTextView', :git => 'https://github.com/hpique/PSPDFTextView.git', :branch=>'agnes'
pod 'MMDrawerController', '~> 0.5'
pod 'MCSwipeTableViewCell', :git => 'https://github.com/hpique/MCSwipeTableViewCell.git'
pod 'SSZipArchive', '~> 0.3'
pod 'HPReorderTableView', '~> 0.1'
pod 'iOS7Colors', '~> 2.0.0'
pod 'TTTAttributedLabel', :git => 'https://github.com/hpique/TTTAttributedLabel.git'
pod 'MHWDirectoryWatcher', '~> 0.0'
pod 'ColorUtils', :git => 'https://github.com/hpique/ColorUtils.git', :branch=>'agnes'
pod 'Haneke', :git => 'https://github.com/hpique/Haneke.git'
pod 'iRate', '~> 1.9'
pod 'Lyt', :git => 'https://github.com/robotmedia/Lyt.git'