platform :ios, '7.0'
pod 'PSPDFTextView', :git => 'https://github.com/steipete/PSPDFTextView.git'
pod 'MMDrawerController', '~> 0.5'
pod 'MCSwipeTableViewCell', '~> 2.0'
pod 'SSZipArchive', '~> 0.3'
pod 'HPReorderTableView', :git => 'https://github.com/hpique/HPReorderTableView.git'
